<?php
/**
 * PlayerInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * A-maze-ing API
 *
 * This document describes the API of the A-maze-ing evening server.    This API consists of three different endpoints, which are detailed below.   - To register yourself as a player use the Player endpoint.   - To get information about the available mazes and enter a specific maze use the Mazes endpoint.   - To navigate a maze use the Maze endpoint.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PlayerInfoTest Class Doc Comment
 *
 * @category    Class
 * @description The data structure that represents information related to a player.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlayerInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlayerInfo"
     */
    public function testPlayerInfo()
    {
    }

    /**
     * Test attribute "player_id"
     */
    public function testPropertyPlayerId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_in_maze"
     */
    public function testPropertyIsInMaze()
    {
    }

    /**
     * Test attribute "maze"
     */
    public function testPropertyMaze()
    {
    }

    /**
     * Test attribute "has_found_easter_egg"
     */
    public function testPropertyHasFoundEasterEgg()
    {
    }

    /**
     * Test attribute "maze_score_in_hand"
     */
    public function testPropertyMazeScoreInHand()
    {
    }

    /**
     * Test attribute "maze_score_in_bag"
     */
    public function testPropertyMazeScoreInBag()
    {
    }

    /**
     * Test attribute "player_score"
     */
    public function testPropertyPlayerScore()
    {
    }
}
