<?php
/**
 * PossibleActionsAndCurrentScoreTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PossibleActionsAndCurrentScoreTest Class Doc Comment
 *
 * @category    Class
 * @description From the current tile where you stand, what actions are available on it and on the surrounding tiles.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PossibleActionsAndCurrentScoreTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PossibleActionsAndCurrentScore"
     */
    public function testPossibleActionsAndCurrentScore()
    {
    }

    /**
     * Test attribute "possible_move_actions"
     */
    public function testPropertyPossibleMoveActions()
    {
    }

    /**
     * Test attribute "can_collect_score_here"
     */
    public function testPropertyCanCollectScoreHere()
    {
    }

    /**
     * Test attribute "can_exit_maze_here"
     */
    public function testPropertyCanExitMazeHere()
    {
    }

    /**
     * Test attribute "current_score_in_hand"
     */
    public function testPropertyCurrentScoreInHand()
    {
    }

    /**
     * Test attribute "current_score_in_bag"
     */
    public function testPropertyCurrentScoreInBag()
    {
    }
}
