<?php
/**
 * MazeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MazeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MazeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for collectScore
     *
     * 💰 Collect score from your hand to your bag..
     *
     */
    public function testCollectScore()
    {
    }

    /**
     * Test case for enter
     *
     * 🌟 Enter a maze..
     *
     */
    public function testEnter()
    {
    }

    /**
     * Test case for exitMaze
     *
     * 🚪 Exit the maze..
     *
     */
    public function testExitMaze()
    {
    }

    /**
     * Test case for moveDown
     *
     * ⬇ Move down..
     *
     */
    public function testMoveDown()
    {
    }

    /**
     * Test case for moveLeft
     *
     * ⬅ Move left..
     *
     */
    public function testMoveLeft()
    {
    }

    /**
     * Test case for moveRight
     *
     * ➡ Move right..
     *
     */
    public function testMoveRight()
    {
    }

    /**
     * Test case for moveUp
     *
     * ⬆ Move up..
     *
     */
    public function testMoveUp()
    {
    }

    /**
     * Test case for possibleActions
     *
     * 👀 Get the list of possible actions, from the tile where you are standing..
     *
     */
    public function testPossibleActions()
    {
    }
}
